### ISSUE TITLE
Possible Refactor

### ISSUE THREAD

**Issue by gauntface** [glenmurphy/route#10]
Hello,

Just took a look at Route.io after hearing good things and just thought I'd put this out there.

With ES2015, you could make a class that all devices extend and remove some of the boilerplate that seems be in the examples.

```
class RouteDevice extends EventEmitter {
    constructor(deviceName) {
       this.name = deviceName;
    }
}

class AlexaDevice extends RouteDevice {
    constructor(options, deviceName) {
        this._deviceName = deviceName ? deviceName : "Alexa";
        super(this._deviceName);
        ....
    }
}

const alexaDevice = new AlexaDevice({
    /// Options here
});

// addDevice would check that the object past in extends RouteDevice
route.addDevice(alexaDevice);
```

Another bonus with this is that if there was a an issue with the options passed into the AlexaDevice, the AlexaDevice constructor could throw an error and the stack trace will be fairly clear. At the moment it would automatically be nested in the route core.

Just an idea - feel free to close if it's more complication than it's really worth or changing the API this much isn't a good idea.

**Comment by glenmurphy** [comment]
That's a cool idea; I'm supportive (though have been out of the JS game for long enough that it will take me a while to drive it myself).

**Comment by gauntface** [comment]
Gonna close this (feel bad leaving an issue open on a clean slate ;) )

I've forked this repo and just playing around with everything here: https://github.com/gauntface/route

If it works out I'm more than happy to merge back in but atm It's just a playground.

p.s. as I'm following the pattern of this - it's a great way of breaking apart dependencies.
